# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Test' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'test' do
    @driver.get('http://127.0.0.1:3000/')
    @driver.find_element(:css, 'body').click
    @driver.find_element(:id, 'btn').click
    @driver.find_element(:id, 'login').click
    @driver.find_element(:id, 'login').send_keys('123')
    @driver.find_element(:id, 'pass').click
    @driver.find_element(:id, 'pass').send_keys('2222')
    @driver.find_element(:css, 'p > #btn').click
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, '.alert') }
  end
end
