# Generated by Selenium IDE

# require_relative 'models/user'
require_relative 'spec_helper'
require_relative 'rails_helper'
require 'selenium-webdriver'
require 'json'
describe 'TestCorrectRegistration' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testCorrectRegistration' do
    @driver.get('http://127.0.0.1:3000/')
    @driver.find_element(:css, '.d-flex:nth-child(4) > #btn').click
    @driver.find_element(:id, 'login').click
    @driver.find_element(:id, 'login').click
    @driver.find_element(:id, 'login').click
    @driver.find_element(:id, 'login').send_keys('SeleniumTest')
    @driver.find_element(:id, 'name').click
    @driver.find_element(:id, 'name').send_keys('SeleniumTest')
    @driver.find_element(:id, 'pass').click
    @driver.find_element(:id, 'pass').send_keys('123')
    @driver.find_element(:id, 'pass_conf').click
    @driver.find_element(:id, 'pass_conf').send_keys('123')
    @driver.find_element(:id, 'mail').click
    @driver.find_element(:id, 'mail').send_keys('asd@asd.ru')
    @driver.find_element(:css, 'p > #btn').click
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, '.row > form') }
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, '.circular_image') }
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, '.row > img') }
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:id, 'btn') }
  end
end

describe 'TestLoggedAdmin' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testLoggedAdmin' do
    @driver.get('http://127.0.0.1:3000/')
    element = @driver.find_element(:css, 'html')
    element = @driver.find_element(:css, 'html')
    element = @driver.find_element(:css, 'html')
    @driver.find_element(:css, 'html').click
    @driver.find_element(:id, 'btn').click
    @driver.find_element(:id, 'login').click
    @driver.find_element(:id, 'login').send_keys('Alex')
    @driver.find_element(:id, 'pass').click
    @driver.find_element(:id, 'pass').send_keys('123')
    @driver.find_element(:css, 'p > #btn').click
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, '.navbar-nav > form > .btn') }
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, '.container:nth-child(2) > .container:nth-child(3) > .row:nth-child(1) .col-auto:nth-child(3) .btn:nth-child(2)') }
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, '.container:nth-child(2) > .container > .row:nth-child(1) .col-auto .col-auto:nth-child(2) #btn') }
  end
end
